Repository pulp-platform/carfield, pull requests merged in 2023-09, with the labels that each got.

#145 Bump Safety Island to fix FPU bug
  Bender.local
  Bender.lock
  Bender.yml
Labels: bug

#130 Integrate Ethernet IP
  Bender.local
  Bender.lock
  Bender.yml
  bender-synth.mk
  carfield.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: enhancement

#148 hw: Disable VGA
  hw/carfield_pkg.sv
Labels: design

#149 Bender.local: Point to latest release of `tech_cells_generic`
  Bender.local
Labels: bug

#147 Improve ethernet integration
  Bender.lock
  Bender.yml
  hw/carfield.sv
  hw/regs/carfield_reg_pkg.sv
  hw/regs/carfield_reg_top.sv
  hw/regs/carfield_regs.csv
  hw/regs/carfield_regs.hjson
  sw/include/regs/soc_ctrl.h
Labels: enhancement

#150 Bender: Bump various IPs
  Bender.local
  Bender.lock
  Bender.yml
Labels: enhancement

#108 Clock gate and isolate Islands on reset
  .gitignore
  carfield.mk
  hw/carfield.sv
  hw/regs/carfield_reg_top.sv
  hw/regs/carfield_regs.csv
  hw/regs/carfield_regs.hjson
  sw/include/car_util.h
  sw/tests/bare-metal/hostd/addressability_test.c
  sw/tests/bare-metal/hostd/helloworld.c
  sw/tests/bare-metal/hostd/pulp-offload.c
  sw/tests/bare-metal/hostd/safed_offloader_blocking.c
  sw/tests/bare-metal/hostd/sw_rst_seq.c
  sw/tests/bare-metal/hostd/system_timer_test.c
  tb/carfield_tb.sv
Labels: enhancement

#158 Bender: Bump cheshire
  Bender.local
  Bender.lock
  Bender.yml
Labels: bug

#151 Connect AXI user bits for ECC and ATOP
  Bender.lock
  Bender.yml
  Makefile
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cfg/spatz_carfield.hjson
  hw/l2_wrap.sv
Labels: design

#161 Enable Cluster Debug request
  Bender.yml
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: design

#163 Bender: Bump cheshire
  Bender.lock
  Bender.yml
Labels: bug-fix

#166 hw: Set non-zero VGA widths to prevent errors at top level
  hw/carfield_pkg.sv
Labels: bug-fix

#168 Boost RTC frequency for Linux boot
  hw/carfield_pkg.sv
  tb/carfield_fix.sv
Labels: enhancement
