Repository pulp-platform/carfield, pull requests merged in 2023-06, with the labels that each got.

#67 hw: Connect safety island bootmode signal
  hw/carfield.sv
Labels: enhancement

#8 Wire interrupts in Carfield
  Bender.lock
  Bender.yml
  carfield.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cheshire_wrap.sv
Labels: enhancement

#65 Hart IDs Alignment.
  Bender.local
  Bender.lock
  Bender.yml
  carfield.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: enhancement

#78 Fix for PULP cluster addressability.
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: bug-fix

#77 Allow addressability test to fail
  Bender.lock
  hw/carfield.sv
  hw/carfield_pkg.sv
  sw/include/car_memory_map.h
  sw/link/l2.ld
  sw/tests/hostd/addressability_test.c
Labels: bug-fix

#74 Improve SW helper functions and mixed fixes
  carfield.mk
  hw/carfield.sv
  sw/include/car_memory_map.h
  sw/include/car_util.h
  sw/include/csr.h
  sw/include/io.h
  sw/include/regs/soc_ctrl.h
  sw/tests/hostd/addressability_test.c
  sw/tests/hostd/mbox_test.c
  sw/tests/hostd/system_timer_test.c
Labels: enhancement, design-fix
