Repository pulp-platform/carfield, pull requests merged in 2023-08, with the labels that each got.

#111 Propagate sync register parameter for CDC FIFOs
  Bender.local
  Bender.lock
  Bender.yml
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cheshire_wrap.sv
  hw/hyperbus_wrap.sv
  hw/l2_wrap.sv
Labels: design

#113 Various updates - 4
  Bender.yml
  carfield.mk
  hw/carfield.sv
  sw/tests/bare-metal/safed/sw.mk
  tb/carfield_fix.sv
  tb/carfield_tb.sv
  tb/vip_security_island_soc.sv
Labels: enhancement, design

#90 PULP Cluster Offloading
  Bender.local
  Bender.lock
  Bender.yml
  README.md
  carfield.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cheshire_wrap.sv
  scripts/elf2header.py
  scripts/env-iis.sh
  scripts/pulpd-env.sh
  scripts/safed-env.sh
  sw/include/car_memory_map.h
  sw/include/car_properties.h
  sw/include/car_util.h
  sw/include/regs/soc_ctrl.h
  sw/sw.mk
  sw/tests/bare-metal/hostd/pulp-offload.c
  sw/tests/bare-metal/pulpd/sw.mk
  sw/tests/bare-metal/safed/sw.mk
  sw/tests/bare-metal/secd/sw.mk
Labels: enhancement

#117 Rename incorrect hyperbus reset bidirectional IO signal
  tb/carfield_fix.sv
  tb/vip_carfield_soc.sv
Labels: design

#118 Bender: Bump `axi_rt` AXI real-time unit
  Bender.lock
  Bender.yml
  carfield.mk
  hw/carfield_pkg.sv
Labels: enhancement

#120 Add mibench automotive benchmark compilation flow
  carfield.mk
  sw/benchmarks/.gitkeep
  sw/sw.mk
Labels: enhancement

#123 Bender: Bump `pulp_cluster` dependency
  Bender.local
  Bender.lock
  Bender.yml
  bender-common.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: bug

#104 Various Fixes - 2
  carfield.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/l2_wrap.sv
  hw/regs/carfield_reg_pkg.sv
  hw/regs/carfield_reg_top.sv
  hw/regs/carfield_regs.csv
  hw/regs/carfield_regs.hjson
  sw/include/car_util.h
  sw/include/regs/soc_ctrl.h
  sw/tests/bare-metal/hostd/sw_rst_seq.c
Labels: enhancement, design

#112 Point to open-source deps - 1
  Bender.lock
  Bender.yml
Labels: enhancement

#132 Bender.yml: Bump hyperbus
  Bender.lock
  Bender.yml
Labels: enhancement
