Repository pulp-platform/carfield, pull requests merged in 2023-07, with the labels that each got.

#81 Fix host clock and reset in edge propagators for safety island interrupts
  hw/carfield.sv
Labels: bug-fix

#80 treewide: Bump security island dependency
  Bender.lock
  Bender.yml
  sw/tests/hostd/mbox_test.c
  tb/carfield_fix.sv
  tb/carfield_tb.sv
Labels: enhancement, design-fix

#87 Various fixes - 1
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cheshire_wrap.sv
  tb/carfield_fix.sv
Labels: design-fix

#84 Add sw reset tests
  Makefile
  carfield.mk
  hw/carfield.sv
  sw/include/car_memory_map.h
  sw/include/car_util.h
  sw/include/regs/safety_soc_ctrl.h
  sw/include/regs/spatz_cluster_peripheral.h
  sw/tests/hostd/addressability_test.c
  sw/tests/hostd/sw_rst_seq.c
Labels: bug, enhancement

#95 hw: Fix out of bounds array
  hw/carfield.sv
Labels: design

#70 Bare-metal offloading flow - 1
  .github/workflows/lint.yml
  .gitignore
  Bender.yml
  CHANGELOG_WEEKLY.md
  README.md
  bender-common.mk
  bender-safed.mk
  bender-synth.mk
  carfield.mk
  hw/carfield.sv
  hw/carfield_pkg.sv
  requirements.txt
  scripts/elf_to_header.py
  scripts/env-iis.sh
  scripts/start_carfield.tcl
  sw/include/car_memory_map.h
  sw/include/car_util.h
  sw/sw.mk
  sw/tests/bare-metal/hostd/addressability_test.c
  sw/tests/bare-metal/hostd/helloworld.c
  sw/tests/bare-metal/hostd/mbox_test.c
  sw/tests/bare-metal/hostd/safed_offloader_blocking.c
  sw/tests/bare-metal/hostd/sw_rst_seq.c
  sw/tests/bare-metal/hostd/system_timer_test.c
  sw/tests/bare-metal/safed/sw.mk
  sw/tests/secd/sw.mk
  tb/carfield_fix.sv
  tb/carfield_tb.sv
  tb/vip_carfield_soc.sv
Labels: enhancement

#57 Add PLL base address and extend clock helper functions
  hw/carfield_pkg.sv
  sw/include/car_memory_map.h
  sw/include/car_util.h
Labels: enhancement
