Repository pulp-platform/carfield, pull requests merged in 2023-10, with the labels that each got.

#169 Bump integer cluster
  Bender.lock
  Bender.yml
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: enhancement

#171 Fix FPGA implementation
  Bender.lock
  Bender.yml
Labels: bug, bug-fix

#121 Add offload flow to Spatz cluster
  Bender.lock
  Bender.yml
  carfield.mk
  hw/carfield.sv
  hw/cfg/spatz_carfield.hjson
  hw/regs/carfield_reg_pkg.sv
  hw/regs/carfield_reg_top.sv
  hw/regs/carfield_regs.csv
  hw/regs/carfield_regs.hjson
  scripts/spatzd-env.sh
  scripts/start_carfield.tcl
  sw/include/car_memory_map.h
  sw/include/regs/soc_ctrl.h
  sw/include/regs/spatz_cluster_peripheral.h
  sw/tests/bare-metal/hostd/spatz-offload.c.wip
  tb/carfield_tb.sv
Labels: enhancement, design

#170 Parameterize default clock divider integer value for domains
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: design

#183 Fix integer cluster offloading
  Bender.local
  Bender.lock
  Bender.yml
  hw/carfield.sv
  hw/carfield_pkg.sv
  sw/tests/bare-metal/hostd/sw_rst_seq.c
Labels: bug, bug-fix

#188 hw: Fix instantiation of reg cdc for external reg interface
  hw/cheshire_wrap.sv
Labels: bug, bug-fix

#190 Fix AXI-OBI conversion in safety island
  Bender.lock
  Bender.yml
Labels: bug-fix

#194 Bump PULP cluster to fix macro implementation
  Bender.local
  Bender.lock
  Bender.yml
Labels: enhancement, bug-fix

#195 hw: Minor fixes to carfield top
  hw/carfield.sv
Labels: design, bug-fix

#191 Fix spatz standalone execution
  Bender.lock
  Bender.yml
  carfield.mk
  hw/carfield.sv
  hw/cfg/spatz_carfield.hjson
  scripts/spatzd-env.sh
  scripts/start_carfield.tcl
  sw/tests/bare-metal/spatzd/build
  tb/carfield_tb.sv
Labels: bug-fix

#154 Add standalone integer cluster preload in TB
  carfield.mk
  scripts/elf2slm.py
  scripts/start_carfield.tcl
  sw/.gitignore
  sw/sw.mk
  sw/tests/bare-metal/pulpd/sw.mk
  sw/tests/bare-metal/safed/sw.mk
  tb/carfield_fix.sv
  tb/carfield_tb.sv
  tb/vip_carfield_soc.sv
Labels: enhancement

#205 Fix standalone intcluster bootflow (JTAG/SL/Hyper preloading)
  carfield.mk
  scripts/elf2header.py
  scripts/elf2slm.py
  scripts/start_carfield.tcl
  sw/tests/bare-metal/pulpd/sw.mk
  tb/carfield_tb.sv
Labels: enhancement

#206 Fix RTL offloading tests
  scripts/elf2header.py
  scripts/elf2slm.py
  sw/tests/bare-metal/pulpd/sw.mk
  tb/carfield_tb.sv
Labels: bug-fix
