Repository pulp-platform/carfield, pull requests merged in 2023-05, with the labels that each got.

#9 Add minimal `sw` flow for Carfield
  .gitlab-ci.yml
  Bender.lock
  Bender.yml
  Makefile
  README.md
  hw/carfield.sv
  hw/carfield_pkg.sv
  scripts/start_carfield.tcl
  sw/include/car_memory_map.h
  sw/include/car_util.h
  sw/lib/.gitkeep
  sw/link/l2.ld
  sw/security_island/bootrom/boot_rom.vmem
  sw/security_island/otp/otp-img.mem
  sw/sw.mk
  sw/tests/check_addressability.c
  sw/tests/helloworld.c
  tb/carfield_fix.sv
  tb/carfield_tb.sv
Labels: enhancement

#19 Add Code Execution from shared L2
  Bender.lock
  Bender.yml
  Makefile
  hw/carfield_pkg.sv
Labels: enhancement

#11 Add system peripherals
  Bender.lock
  Bender.yml
  Makefile
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cheshire_wrap.sv
  sw/include/car_memory_map.h
  sw/include/regs/system_timer.h
  sw/tests/addressability_test.c
  sw/tests/system_timer_test.c
Labels: enhancement

#27 hw: Bump security island
  Bender.lock
  Bender.yml
  hw/carfield.sv
  hw/carfield_pkg.sv
Labels: bug

#23 Integrate Spatz cluster
  Bender.local
  Bender.lock
  Bender.yml
  Makefile
  hw/carfield.sv
  hw/carfield_pkg.sv
  sw/include/car_memory_map.h
  sw/tests/addressability_test.c
Labels: enhancement

#28 Align FPU version for carfield
  .gitignore
  Bender.local
  Bender.lock
  Bender.yml
Labels: enhancement

#33 Bump main IPs
  Bender.local
  Bender.lock
  Bender.yml
  Makefile
  hw/carfield.sv
Labels: enhancement

#36 Fix Safety Island's power on reset connection and eliding Spyglass.
  Bender.local
  Bender.lock
  Bender.yml
  Makefile
  hw/carfield.sv
Labels: bug-fix

#40 Add power-on reset and mailbox interrupt to integer cluster
  Bender.lock
  Bender.yml
  hw/carfield.sv
Labels: enhancement

#35 Fix and improve `hyperbus_wrap`
  Bender.yml
  hw/carfield.sv
  hw/hyperbus_wrap.sv
  tb/carfield_fix.sv
Labels: bug-fix, enhancement

#10 Add `carfield_regs` unit (system level control and status registers)
  .dir-locals.el
  .github/license-checker.hjson
  .github/workflows/lint.yml
  .gitignore
  Bender.yml
  Makefile
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/carfield_rstgen.sv
  hw/regs/carfield_reg_pkg.sv
  hw/regs/carfield_reg_top.sv
  hw/regs/carfield_regs.csv
  hw/regs/carfield_regs.hjson
  scripts/csv_to_json.py
  scripts/env-iis.sh
  tb/carfield_fix.sv
Labels: enhancement

#42 Bump `hyperbus` to avoid compiling missing memory models `.sv` files.
  Bender.lock
  Bender.yml
  Makefile
Labels: bug-fix

#45 Add synthesis flow steps to carfield CI flow
  .github/workflows/gitlab-ci.yml
  Makefile
Labels: enhancement

#12 Update mailbox unit
  Bender.lock
  Bender.yml
  Makefile
  README.md
  hw/carfield.sv
  hw/carfield_pkg.sv
  hw/cheshire_wrap.sv
  scripts/start_carfield.tcl
  sw/security_island/bootrom/boot_rom.vmem
  sw/security_island/otp/otp-img.mem
  sw/sw.mk
  sw/tests/hostd/addressability_test.c
  sw/tests/hostd/helloworld.c
  sw/tests/hostd/mbox_test.c
  sw/tests/hostd/system_timer_test.c
  sw/tests/secd/sw.mk
  tb/carfield_fix.sv
  tb/carfield_tb.sv
  tb/security_island_tb.sv
Labels: enhancement

#41 Add atomics support to shared L2 memory
  Bender.lock
  Bender.yml
  hw/carfield.sv
  hw/l2_wrap.sv
  sw/tests/hostd/system_timer_test.c
Labels: enhancement
